version: '3.4'
services:
  discord.botabordelv2:
    image: '${DOCKER_REGISTRY-}discordbotabordelv2'
    build:
      context: .
      dockerfile: Discord.BotABordelV2/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - '${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
      - '.\Discord.BotABordelV2\Resources:/app/Resources'

  lavalink:
    image: 'ghcr.io/freyacodes/lavalink:e62f868'
    ports:
      - '2333:2333/udp'
      - '2333:2333'
    environment: []
    volumes:
      - '.\Lavalink\application.yaml:/opt/Lavalink/application.yaml'
      - '.\Discord.BotABordelV2\Resources:/app/Resources'

